# Semana no. 2
## Hoy iniciamos con la siguiente lectura de archivos, en este caso:
### Excel
### Json
### Html


Al igual que la semana anterior, estaremos primero cargando los archivos para poder leerlos, observar que información tenemos y así utilizar únicamente la información que necesitamos conservar.

<font size = "5"> **Puntos a recordar:**

1. La ruta debe de estar en una variable por facilidad
2. Siempre hacer una copia del DF si vamos a eliminar o agregar datos.

# Archivos Excel
## vamos a conectarnos a un archivo en primera instancia en una ubicación externa, ya que
## localmente es un poco más sencillo

In [1]:
# Usaremos el siguiente link:
# "https://github.com/wantaprender-tech/Curso-Bigdata-Python/raw/refs/heads/main/Semana%20No.%201/base%20de%20datos%20excel.xlsx"

import pandas as pd
url_excel="https://github.com/wantaprender-tech/Curso-Bigdata-Python/raw/refs/heads/main/Semana%20No.%201/base%20de%20datos%20excel.xlsx"
dfexcel=pd.read_excel(url_excel)

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>

In [2]:
# a veces, da un error de conexión (esto depende de donde nos estemos conectando) o actualizaciones, etc, por lo que a veces
# es complicado leerlos en una web, es más recomendado hacerlo de forma local.
# en mi caso, por la versión de python haré las siguientes actualizaciones (funcion pip --upgrade) y un protocolo ssl para
# leer el archivo, pero esto puede variar en cada equipo.  Si no funciona en tu equipo, no te preocupes lo haremos local 
# para poder trabajar.

!pip install --upgrade openpyxl pandas numpy
import ssl
import pandas as pd
import numpy as np
np.float=float

ssl._create_default_https_context=ssl._create_unverified_context
url_excel="https://github.com/wantaprender-tech/Curso-Bigdata-Python/raw/refs/heads/main/Semana%20No.%201/base%20de%20datos%20excel.xlsx"
dfexcel=pd.read_excel(url_excel)

Requirement already up-to-date: openpyxl in c:\users\alfon\anaconda3\lib\site-packages (3.1.5)
Requirement already up-to-date: pandas in c:\users\alfon\anaconda3\lib\site-packages (2.0.3)
Requirement already up-to-date: numpy in c:\users\alfon\anaconda3\lib\site-packages (1.24.4)
Requirement already satisfied, skipping upgrade: et-xmlfile in c:\users\alfon\anaconda3\lib\site-packages (from openpyxl) (1.0.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.8.2 in c:\users\alfon\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied, skipping upgrade: tzdata>=2022.1 in c:\users\alfon\anaconda3\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied, skipping upgrade: pytz>=2020.1 in c:\users\alfon\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\users\alfon\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)

In [3]:
# ahora, veamos que tiene el archivo:
dfexcel.head(5)

,No.,Empleado,Cliente,Fecha,Producto,Unidades,Departamento,PV,Costo,Venta,costo valor,Margen,Margen prom
0,1,Jorge Gonzalez,Cliente C,43509,Amoxicilina,91,Guatemala,61.4,0.55,5587.4,3073.07,2514.33,0.45
1,2,Jorge Gonzalez,Cliente B,43528,Acetaminofen,101,Zacapa,1.0,0.45,101.0,45.45,55.55,0.55
2,3,Carolina Strauss,Cliente B,43638,Amoxicilina,77,Guatemala,61.4,0.55,4727.8,2600.29,2127.51,0.45
3,4,Carolina Strauss,Cliente B,43639,Jarabe Tos,136,Guatemala,105.0,0.70,14280.0,9996.00,4284.00,0.30
4,5,Dante Rodriguez,Cliente C,43604,Amoxicilina,116,Guatemala,61.4,0.55,7122.4,3917.32,3205.08,0.45

In [4]:
# ahora, lo leeremos pero localmente, descargue el archivo de su github y tome la ruta de trabajo donde la descargue y
# trabajaremos a partir de esa carga:

url_local="C:/Users/alfon/OneDrive/Escritorio/excel python/base de datos excel.xlsx"
df_excel_local=pd.read_excel(url_local)
df_excel_local.head(5)

,No.,Empleado,Cliente,Fecha,Producto,Unidades,Departamento,PV,Costo,Venta,costo valor,Margen,Margen prom
0,1,Jorge Gonzalez,Cliente C,43509,Amoxicilina,91,Guatemala,61.4,0.55,5587.4,3073.07,2514.33,0.45
1,2,Jorge Gonzalez,Cliente B,43528,Acetaminofen,101,Zacapa,1.0,0.45,101.0,45.45,55.55,0.55
2,3,Carolina Strauss,Cliente B,43638,Amoxicilina,77,Guatemala,61.4,0.55,4727.8,2600.29,2127.51,0.45
3,4,Carolina Strauss,Cliente B,43639,Jarabe Tos,136,Guatemala,105.0,0.70,14280.0,9996.00,4284.00,0.30
4,5,Dante Rodriguez,Cliente C,43604,Amoxicilina,116,Guatemala,61.4,0.55,7122.4,3917.32,3205.08,0.45

In [5]:
# ahora, algunos calculos:

df_excel_local['Producto'].value_counts()

Producto
Amoxicilina      59
Jarabe Tos       57
Ibuprofeno       48
Acetaminofen     47
Loratadina       22
Loratadina Mk    17
Name: count, dtype: int64

In [6]:
df_excel_local.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   No.           250 non-null    int64
 1   Empleado      250 non-null    object
 2   Cliente       250 non-null    object
 3   Fecha         250 non-null    int64
 4   Producto      250 non-null    object
 5   Unidades      250 non-null    int64
 6   Departamento  250 non-null    object
 7   PV            250 non-null    float64
 8   Costo         250 non-null    float64
 9   Venta         250 non-null    float64
 10  costo valor   250 non-null    float64
 11  Margen        250 non-null    float64
 12  Margen prom   250 non-null    float64
dtypes: float64(6), int64(3), object(4)
memory usage: 25.5+ KB

In [7]:
df_excel_local.describe()

,No.,Fecha,Unidades,PV,Costo,Venta,costo valor,Margen,Margen prom
count,250.000000,250.000000,250.000000,250.00000,250.000000,250.00000,250.000000,250.000000,250.000000
mean,125.500000,43653.804000,101.168000,40.46340,0.526360,3962.99760,2501.375580,1461.622020,0.473640
std,72.312977,104.946255,27.988878,42.23257,0.121321,4355.43799,2980.857666,1449.617220,0.121321
min,1.000000,43467.000000,50.000000,1.00000,0.380000,51.00000,22.950000,28.050000,0.300000
25%,63.250000,43560.250000,77.000000,3.75000,0.400000,377.81250,155.062500,195.834375,0.350000
50%,125.500000,43660.000000,101.000000,6.75000,0.550000,784.75000,388.293750,472.285000,0.450000
75%,187.750000,43742.000000,126.000000,61.40000,0.650000,7218.75000,4405.025000,2818.260000,0.600000
max,250.000000,43830.000000,150.000000,105.00000,0.700000,15540.00000,10878.000000,4662.000000,0.620000

In [8]:
# ahora, veamos por ejemplo el total de ventas, costos y margen
df_excel_local[['Venta','costo valor','Margen']].sum()

Venta          990749.400
costo valor    625343.895
Margen         365405.505
dtype: float64

In [9]:
# usando el comando .agg(agregación)
resumen=df_excel_local.agg({
    'Venta':'sum',
    'costo valor':'sum',
    'Margen':'mean'
})
print(resumen)

Venta          990749.40000
costo valor    625343.89500
Margen           1461.62202
dtype: float64

---

## Archivos Json:

Un archivo JSON (JavaScript Object Notation) es un formato de texto ligero y estándar para el almacenamiento e intercambio de datos, diseñado para ser fácil de leer por humanos y analizable por máquinas. Se basa en pares de clave-valor y se utiliza ampliamente en aplicaciones web para transferir información entre servidores y aplicaciones.

Estructura: Se organiza mediante objetos (colecciones de pares {"clave": "valor"} encerradas en llaves {}) y arreglos (listas ordenadas de valores encerradas en corchetes [])

¿Para qué sirve?
JSON es el estándar principal para APIs web, configuración de aplicaciones, almacenamiento de datos no estructurados en bases de datos NoSQL (como MongoDB) y la transferencia de información en tiempo real.

Vamos entonces a cargar de primero un archivo Json sencillo ubicado en la carpeta de la semana no. 2

la ruta de acceso es: https://raw.githubusercontent.com/wantaprender-tech/Curso-Bigdata-Python/refs/heads/main/Semana%20no.%202/proyecto.json

In [10]:
#import pandas as pd
url="https://raw.githubusercontent.com/wantaprender-tech/Curso-Bigdata-Python/refs/heads/main/Semana%20no.%202/proyecto.json"
df=pd.read_json(url)
df

               tarea responsable  horas  completada
0  Análisis de Datos         Ana     10        True
1   Limpieza de JSON        Beto     15       False
2        Carga a SQL       Carla      8       False

Ahora, vamos a cargar un documento desde una API, esto se realiza con la función requests

Una API (Interfaz de Programación de Aplicaciones) es un conjunto de reglas, protocolos y herramientas que permite que dos aplicaciones de software se comuniquen e intercambien datos entre sí. Actúa como un intermediario, facilitando que una aplicación utilice funciones o recursos de otra, como mostrar el clima, pagos o mapas, sin necesidad de desarrollarlos desde cero.

Una API es como un menú, donde usted pide algo a una dirección (URL) y el servidor devuelve la información generalmente en un archivo JSON.

la dirección de nuestra API es: https://jsonplaceholder.typicode.com/users

In [11]:
import requests
url2="https://jsonplaceholder.typicode.com/users"
respuesta=requests.get(url2)
df_json=respuesta.json()
df_json

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

Con esta instrucción, tenemos el archivo Json en pantalla, es decir, los datos, pero debemos de transformarlo en una tabla para poder analizar que data existe, para ello usamos el comando DataFrame de pandas

In [12]:
df_jsonf=pd.DataFrame(df_json)
df_jsonf

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

Como pueden ver, la columna Address y la columna Company tienen más datos adentro (anidadas), a esto dentro de los archivos Json se le conoce como diccionarios (2 más columnas anidadas dentro de una misma). 

Para este proceso hay que aplanar el archivo de forma que python separe los datos anidados, puede hacerse de dos formas, utilizando la instrucción json_normalize (que volverá listas las columnas anidadas, esta implica volver a cargar el archivo) y la función tolist(), que cuando ya tenemos cargado el archivo nos ayuda a hacer este proceso.

In [13]:
json_address=pd.json_normalize(df_jsonf['address'].tolist())
json_address=json_address.add_prefix('addr')
json_address.head()

,addrstreet,addrsuite,addrcity,addrzipcode,addrgeo.lat,addrgeo.lng
0,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496
1,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618
2,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653
3,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990
4,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342

In [14]:
df_jsonf.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

Ahora, haremos lo mismo pero con la compañía

In [15]:
json_company=pd.json_normalize(df_jsonf['company'].tolist())
json_company=json_company.add_prefix('comp_')
json_company.head()

,comp_name,comp_catchPhrase,comp_bs
0,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems

A veces, sucede un error cuando la columna tiene más de un diccionario (la forma de un diccionario es [{}], a veces puede venir por ejemplo alguna columna nula o [[{}]], y eso da error), para ello vamos a utilizar otra forma de hacerlo:

In [ ]:
#lista_company=list(df_jsonf['company'])
#json_company=pd.json_normalize(lista_company)
#json_company=json_company.add_prefix('comp_')
#json_company.head()

Ahora, hay que unir los datos que se arreglaron al dataframe original, para ello usaremos la función concat, y eliminaremos las columnas que ya no sirven.

**Ojo, recordar copiar o crear un nuevo dataframe antes de hacer cualquier cambio por si cometemos un error.
Ojo, es importante notar que la función concat requiere una instrucción llamada Axis, siendo 0 para llenar por filas, siendo 1 para llenar por columnas.**

In [16]:
df_jsonfinal=pd.concat([df_jsonf,json_address,json_company], axis=1)
df_jsonfinal=df_jsonfinal.drop(['address','company'],axis=1)
df_jsonfinal.head()

,id,name,username,email,phone,website,addrstreet,addrsuite,addrcity,addrzipcode,addrgeo.lat,addrgeo.lng,comp_name,comp_catchPhrase,comp_bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems

In [17]:
df_jsonf

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

## Vamos ahora con HTML, un proceso muy parecido, pero ahora estamos leyendo directamente de la pagina web, acá se realiza un proceso de búsqueda de lo que necesitamos, ya que la mayoría de datos que se pueden descargar de una web está en tablas (tablas de navegación, tablas de contenido y tablas de datos)

La principal diferencia entre los tres tipos de tabla radica en su propósito semántico y accesibilidad: las tablas de datos organizan información estructurada (filas/columnas) usando <th> y <td> para lectores de pantalla. Las tablas de navegación (a menudo div/css) organizan enlaces y las tablas de contenido estructuran menús, evitando el uso de etiquetas <table> para el diseño
   
ruta: "https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n"

In [18]:
url_html="https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n"
tablas=pd.read_html(url_html)
df_paises=tablas[0]
df_paises.head()

HTTPError: HTTP Error 403: Forbidden

In [19]:
url_html="https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}
respuestas=requests.get(url_html,headers=headers)
tablas=pd.read_html(respuestas.text,match="País")
df_poblacion=tablas[0]
display(df_poblacion.head(10))

,N.º,País (o territorio dependiente),Proyección exponencial de la población al 1/7/2025[7]​,Total mun- dial (%),Cambio medio anual (%)[8]​,Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción[9]​,"Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional",Fecha de esta última cifra de población en particular (d/mm/aaaa)[10]​,Tipo[11]​,Enlace o hipervínculo (usualmente de tipo oficial) de esta última cifra de población
0,1,India,1 417 492 000,1755,090,12 692 000,1585,78,1 417 492 000,1/07/2025,A,web.archive.org
1,2,China[12]​,1 406 589 000,1741,-024,-3 390 000,-,-,1 404 890 000,31/12/2025,E,www.stats.gov.cn
2,3,Estados Unidos,342 181 000,424,061,2 084 000,260,114,343 375 000,24/02/2026,R,www.census.gov
3,4,Indonesia,284 447 000,352,107,3 043 000,380,65,284 438 782,30/06/2025,E,www.bps.go.id
4,5,Pakistán,256 204 000,317,256,6 567 000,820,27,241 499 431,1/03/2023,C,www.pbs.gov.pk
5,6,Nigeria,236 213 000,292,273,6 458 000,807,26,223 800 000,1/07/2023,E,cdn.sanity.io
6,7,Brasil,213 421 000,264,039,841 000,105,176,213 421 037,1/07/2025,E,www.ibge.gov.br
7,8,Bangladés,177 567 000,220,147,2 618 000,327,47,169 828 911,15/06/2022,C,bdnews24.com
8,9,Rusia[13]​,146 022 000,181,-001,-12 000,-,-,146 028 325,1/01/2025,E,rosstat.gov.ru
9,10,México,131 013 000,162,074,966 000,121,94,130 054 247,7/2024,E,www.inegi.org.mx

In [20]:
df_poblacion

,N.º,País (o territorio dependiente),Proyección exponencial de la población al 1/7/2025[7]​,Total mun- dial (%),Cambio medio anual (%)[8]​,Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción[9]​,"Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional",Fecha de esta última cifra de población en particular (d/mm/aaaa)[10]​,Tipo[11]​,Enlace o hipervínculo (usualmente de tipo oficial) de esta última cifra de población
0,1,India,1 417 492 000,1755,090,12 692 000,1585,78,1 417 492 000,1/07/2025,A,web.archive.org
1,2,China[12]​,1 406 589 000,1741,-024,-3 390 000,-,-,1 404 890 000,31/12/2025,E,www.stats.gov.cn
2,3,Estados Unidos,342 181 000,424,061,2 084 000,260,114,343 375 000,24/02/2026,R,www.census.gov
3,4,Indonesia,284 447 000,352,107,3 043 000,380,65,284 438 782,30/06/2025,E,www.bps.go.id
4,5,Pakistán,256 204 000,317,256,6 567 000,820,27,241 499 431,1/03/2023,C,www.pbs.gov.pk
...,...,...,...,...,...,...,...,...,...,...,...,...
241,242,Islas Cocos (Australia),600,000,174,0,000,40,593,11/08/2021,C,www.citypopulation.de
242,243,Islas Ultramarinas Menores de los Estados Unidos,100,000,-496,0,000,-,190,1/04/2010,C,www.statoids.com
243,244,Islas Pitcairn (RU),30,000,-111,0,000,-,35,1/07/2023,E,www.immigration.pn
244,NaN,Mundo,8 078 462 000,10000,098,80 054 000,10000,71,8 207 124 000,24/02/2026,R,www.worldometers.info
245,N°,País (o territorio dependiente),Proyección exponencial de la población al 1/7/...,Total mun- dial (%),Cambio medio anual (%),Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción,"Censo más reciente, última estimación oficial,...",Fecha de esta última cifra de población en par...,Tipo,Enlace o hipervínculo (usualmente de tipo ofic...

In [21]:
# Para ver las primeras filas de CADA tabla encontrada en la página
for i, tabla in enumerate(tablas):
    print(f"\n---No. de tabla: {i}---")
    display(tabla.head(2))

---No. de tabla: 0---

,N.º,País (o territorio dependiente),Proyección exponencial de la población al 1/7/2025[7]​,Total mun- dial (%),Cambio medio anual (%)[8]​,Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción[9]​,"Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional",Fecha de esta última cifra de población en particular (d/mm/aaaa)[10]​,Tipo[11]​,Enlace o hipervínculo (usualmente de tipo oficial) de esta última cifra de población
0,1,India,1 417 492 000,1755,090,12 692 000,1585,78,1 417 492 000,1/07/2025,A,web.archive.org
1,2,China[12]​,1 406 589 000,1741,-024,-3 390 000,-,-,1 404 890 000,31/12/2025,E,www.stats.gov.cn

---No. de tabla: 1---

,"Continente, subcontinente o región geográfica",Proyección exponencial de la población al 1/7/2025,Total mun- dial (%),Cambio medio anual (%),Cambio medio absoluto anual,Cambio medio abs. total anual (%),Años para even- tual dupli- ca- ción
0,África,1 490 859 000,1845,244,36 556 000,4566,29
1,África Central,217 365 000,269,255,5 555 000,694,28

---No. de tabla: 2---

,0,1,2,3
0,Tabla de países y territorios dependientes por...,Tabla de países y territorios dependientes por...,Tabla de países y territorios dependientes por...,NaN
1,N.º País (o territorio dependiente) Población ...,N.º País (o territorio dependiente) Población ...,N.º País (o territorio dependiente) Población ...,NaN

---No. de tabla: 3---

,N.º,País (o territorio dependiente),Población estimada por la ONU para mediados del año 1950,% del total mundial
0,1,China,543 979 000,2177
1,2,India,357 021 000,1428

---No. de tabla: 4---

,N.º,País (o territorio dependiente),Población estimada por la ONU para mediados del año 1975,% del total mundial
0,1,China,915 125 000,2249
1,2,India,623 524 000,1532

---No. de tabla: 5---

,N.º,País (o territorio dependiente),Población estimada por la ONU para mediados del año 2000,% del total mundial
0,1,China,1 264 099 000,2056
1,2,India,1 059 634 000,1723

# ahora, vamos a cambiar a SQL
## con sql, vemos que son datos estructurados, tienen relaciones y están establecidos en una base de datos de acceso restringido (link, usuario, clave, puerto), lo cual requiere un proceso de seguridad en la conexión.

### nosotros, vamos a usar sqlite para simular una conexión de sql, con el fin de evitar tener que montar un servidor sql.  

### igualmente, nos conectaremos a una base de datos sql en web pero que es sitio seguro, con el fin de buscar también el trámite de información, pero no requeriremos credenciales.

### la libreria a utilizar en python para sql es sqlite 3

In [22]:
import sqlite3

In [23]:
# para este primer ejemplo, vamos a crear una database local pequeña, que usaremos como conexión tipo sql, con el fin
# de hacer nuestra primera conexión.

datos ={
    'ID proyecto':[101,102,103,104,105,106,107],
    'Nombre': ['Proyecto 1','Proyecto 2','Proyecto 3','Proyecto 4','Proyecto 5','Proyecto 6','Proyecto 7'],
    'Presupuesto': [50000,25000,80000,450000,75000,20000,125000],
    'Estado':["Completado","Completado","En curso","Pendiente","Pendiente","En curso","Pendiente"]
}
# asignamos la data a un dataframe con la función DataFrame
# DataFrame crea una estructura de datos bidimensional, etiquetada y tabular
# similar a una hoja de cálculo o tabla SQL, organizada en filas y columnas

df_proyectos=pd.DataFrame(datos)
df_proyectos

   ID proyecto      Nombre  Presupuesto      Estado
0          101  Proyecto 1        50000  Completado
1          102  Proyecto 2        25000  Completado
2          103  Proyecto 3        80000    En curso
3          104  Proyecto 4       450000   Pendiente
4          105  Proyecto 5        75000   Pendiente
5          106  Proyecto 6        20000    En curso
6          107  Proyecto 7       125000   Pendiente

In [24]:
# ahora, vamos a crear la conexión para simular un archivo sql para manipular la data con las instrucciones de sql
# hay dos instrucciones, if_exists (esta tiene tres status: append (agregar), fail(fallar) y replace(reemplazar)), y la
# función index sirve para decirle a python si agrega el index de el o solamente la data nuestra (True=agregar, False= no)

conexion=sqlite3.connect("GestionProyectos.db")
df_proyectos.to_sql('proyectos',conexion, if_exists='replace',index=False)
print("hecho")

hecho

In [25]:
# ya que tenemos este proceso, ya podemos trabajar los comandos de sql (Select, from, where, etc.), TODOS LOS COMANDOS
# DE SQL SON EN MAYÚSCULAS
# usaremos una variable para almacenar la consulta que queremos

consulta="SELECT * FROM proyectos WHERE Presupuesto > 40000 AND Estado ='En curso'"


# ahora, leemos la consulta.
df_reporte=pd.read_sql(consulta,conexion)
df_reporte

   ID proyecto      Nombre  Presupuesto    Estado
0          103  Proyecto 3        80000  En curso

In [26]:
consulta="SELECT * FROM proyectos WHERE Presupuesto >40000"
df_reporte=pd.read_sql(consulta,conexion)
df_reporte

   ID proyecto      Nombre  Presupuesto      Estado
0          101  Proyecto 1        50000  Completado
1          103  Proyecto 3        80000    En curso
2          104  Proyecto 4       450000   Pendiente
3          105  Proyecto 5        75000   Pendiente
4          107  Proyecto 7       125000   Pendiente

# Ahora, haremos una conexión de un archivo que está en internet (claro, sin credenciales), pero haremos el proceso de extracción de datos y lo colocaremos local.

## usaremos la librería requests para traer la data, y los comando with y write para ller los datos.
## Hay que recordar que los archivos de base de datos son registros binarios, por lo cual no podemos leer como un archivo de texto.

In [ ]:
# importemos requests

# la base de datos que usaremos es la siguiente: 
# "https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite"

# conectamos con la base de datos:


# ahora, traemos la data (wb es "write binary" y la f (file) es el nombre de una variable cualquiera (puede ser cualquier letra))

In [ ]:
# ahora, ya podemos ver el nombre de las tablas que existen, pero ojo, las tablas solo muestran el nombre
# pero no los campos que tiene cada tabla
# vamos a usar sqlite_master que nos ayudará a buscar todos los nombres de las tablas en la db.

In [ ]:
# Si quiero ver que hay en cada tabla, haremos una lectura tabla por tabla para hacerlo
# Con un ciclo podemos hacerlo, pero eso lo veremos en scrapping

In [ ]:
# si repetimos el comando pero cambiamos la opción limit a 1, sucede lo siguiente: